### ISSUE TITLE
Feedback op "Installatie van Nextcloud Demo/Test-omgeving"

### ISSUE THREAD

**Issue by MarcoKlerks** [ConductionNL/opencatalogi#59]
Zie: https://github.com/ConductionNL/opencatalogi/blob/master/docs/developers/installatie-van-nextcloud-demo-test-omgeving.md

Enkele suggesties om de handleiding nog helderder te maken (ook voor leken zoals ik):
1. Bij stap 4, optie 1, werkt de download-link naar het .sh-bestand niet.
2. Bij stap 4, optie 2, was het voor mij niet direct duidelijk welke CLI ik moest gebruiken. Bij de installatie van WSL2 kreeg ik immers ook een CLI voor Ubuntu. Ik vond op mijn PC ook een 'PowerShell' en een 'Opdrachtprompt'. Ik heb mijn installatie via Powershell gedaan (Want die vond ik als eerste).
3. Toen ik de handleiding had doorlopen, kon ik OpenCatalogi niet vinden. Het duurde even voordat ik in de gaten had dat hier een [andere handleiding](https://github.com/ConductionNL/opencatalogi/blob/master/docs/developers/de-opencatalogi-app-toevoegen-aan-nextcloud.md) voor was. Graag hiernaar verwijzen. 
4. In de handleiding ['De OpenCatalogi-app toevoegen aan Nextcloud'](https://github.com/ConductionNL/opencatalogi/blob/master/docs/developers/de-opencatalogi-app-toevoegen-aan-nextcloud.md) wordt gevraagd om de app te koppelen met MongoDB en/of ElasticSearch. Ik ga ervan uit dat dat bij een lokale installatie niet van toepassing is.

**Comment by MWest2020** [comment]
Bedankt voor de feedback. Het voorkomt blinde vlekken. 

1) Zou het helpen als er in de handleiding staat rechtermuisklik opslaan van de link (want dat werkt volgens mij als downlaod-optie)
2) goede. Gaan we meenemen. 
3)  nemen we mee
4)  Dit klopt. Er is inderdaad nu ook de optie in `Settings` te kiezen voor interne storage, of API

**Comment by MarcoKlerks** [comment]
1. Ja
2. Top!
3. Top!
4. Neem het op in de handleiding ;-)

**Comment by MWest2020** [comment]
4. Dat idd handig om erbij te vermelden, maar nemen we natuurlijk mee. Bedankt zoals altijd voor de fb
